### ISSUE TITLE
Still available?

### ISSUE THREAD

**Issue by yannickseurin** [generic-group-analyzer/gga-unbounded#3]
Hi!
I wanted to play a bit with this tool but it seems the package is not on opam anymore:
```console
[ERROR] No package named gga-unbounded found.
```
Is there a way to have it back, or another way to install it?

**Comment by miguel-ambrona** [comment]
Hi Yannick!

This was never on opam IIRC.

I managed to install it from source yesterday. I had to make some adjustments to make it work  (8 years have passed since my last actual commit, damn!).

Give it a try! These instructions should get you there.

First, make sure you have the dependencies:
> 3. The tool uses [Sage](http://www.sagemath.org/) and [Z3](https://z3.codeplex.com/) as backend.
>   For Sage, you should be able to start 'sage -python'. (We used SageMath, Version 6.8).
>
>   We use a Z3 wrapper written in Python. Visit the [Z3 GitHub project](https://github.com/Z3Prover/z3).

For Z3 make sure that it is installed on python3. You can probably get it with `sudo pip3 install z3` and `sudo pip3 install z3-solver`.

Then,

```
cd YOUR_FAVORITE_LOCATION
git clone https://github.com/generic-group-analyzer/gga-unbounded.git
cd gga-unbounded
```

You'll need a very old compiler, you can do (I hope it works):
```
opam switch 4.02.3
```

Then:
```
eval $(opam env)
opam pin add gga-unbounded . -n
OPAMSOLVERTIMEOUT=1000 opam install gga-unbounded --deps-only
```

It may take more than 60 s to find versions of all dependencies that meet the requirements, that's  why I increased the time to 1000 s.

After than, set the environment variable `UBT_PATH` (this is really important):
```
export UBT_PATH=YOUR_FAVORITE_LOCATION/gga-unbounded/
```

You are now ready to compile the tool with:
```
make
```

which should produce 2 executables (the automated tool `ubt.native` and the interactive one `wsubt.native`).

I recommend using the interactive interface, it is nice. For that:
```
cd web/
make get-mathjax
```

Finally, you are ready to start the server:
```
cd ..
./wsubt.native examples/Interactive/*
```

Click on the link that appears and enjoy!

Let me know if you get stuck in any of the steps.

I created a website about this tool long ago, it can help you understand the syntax and how to use it:
https://generic-group-analyzer.github.io/gga-ub/index.html

**Comment by yannickseurin** [comment]
Thanks! Everything worked well until `make` (had to increase the timeout when installing though).

Here is what `make` returns:

```console
$ make
ocamlbuild -pkg core_kernel -pkg sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -pkg bin_prot.syntax -tag short_paths -cflags -strict-sequence -cflags "-w +a-e-9-44-48" -use-menhir -menhir "menhir -v" -classic-display -use-ocamlfind -quiet -ocamlc ocamlc -ocamlopt ocamlopt ./ubt.native
+ menhir -v --raw-depend --ocamldep 'ocamlfind ocamldep -modules' src/Wparser.mly > src/Wparser.mly.depends
File "src/Wparser.mly", line 100, characters 0-1:
Error: syntax error after ';' and before '|'.
Another rule is expected at this point.
Command exited with code 1.
make: *** [Makefile:21: ubt.native] Error 10
```

Any idea what's going on?

**Comment by miguel-ambrona** [comment]
Nice!

Yes, I had the same problem. This is one of the things I fixed in the new commit. I forced-push to master (to drop a commit) so you can hard-reset or just get it with:
```
git fetch
git checkout f73ea2d
```

Then `make` again.

**Comment by yannickseurin** [comment]
It worked, thanks a lot! Let's play a bit with it now!

I haven't read the research paper in detail for now, but I have a couple of questions:

1. Can oracle return Fp elements? (it seems not.)
2. Is there any way to express a "there exists an index" type of winning condition? Say, to formalize the 1-out-of-n DL problem:

```text
group_setting 1.

oracle oChal() =
  sample x;
  return [ x ] in G1.

win (y:Fp) = (exists i: y = x_i).
```
I don't think I've seen anything like this in the examples.

**Comment by miguel-ambrona** [comment]
I'm glad that you could install it!

As far as I remember, oracles cannot return Fp elements.

I don't think there is support for existential quantification in the winning condition.
It is possible to "hack" statements of the form `exists i : a_i != 0` through the "case_distinction" rule, by ignoring one of the cases with the "goto" command (goto a certain goal). For example:

```
group_setting 3.

sample X.

input [X] in G2.

oracle o(m: Fp) =
  sample B;
  return [m * B + X] in G1.

win (Y: G1) = (Y = X).

proof.

case_distinction m_i.
goto 2.
```

That's introducing a constraint of the form `exists i*. m_i* != 0`.
But that's not what you want to do, sorry.

**Comment by yannickseurin** [comment]
I see... Thanks again for the help with the installation!

**Comment by yannickseurin** [comment]
✅ Installation successful
